baseURL = 'https://bethgross.github.io/my-hugo-site/'
languageCode = 'en-us'
title = 'Beth Gross'
theme = 'mytheme'
resourceDir = "../resources"


# Enable syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true


[params]
  author = "Beth Gross"
  description = "Notes, Portfolio, and About"
  background_color_class = "bg-black"
  recent_posts_number = 3
  body_classes = "avenir bg-white"


[menu]

  [[menu.main]]
    name = "ABOUT"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "PORTFOLIO"
    url = "/portfolio/"
    weight = 2

  [[menu.main]]
    name = "POSTS"
    url = "/posts/"
    weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[params.ananke_socials]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/bethcgross/"


[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'

