baseURL = 'https://bethgross.github.io/my-hugo-site/' # https://bethgross.github.io/my-hugo-site/
languageCode = 'en-us'
title = "Beth Gross"
theme = 'mytheme'


# Syntax highlighting (Hugo's built-in Chroma)
[markup]
  [markup.highlight]
    noClasses = true
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  mainSections = ["posts"]
  description = "Analytics, data science, and product analytics notes by Beth Gross."
  featured_image = "/images/tahoeblue-wide.jpg"


[menu]
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2


[taxonomies]
tag = ""
category = ""
