baseURL = '/'
languageCode = 'en-us'
title = "Beth Gross"
theme = 'mytheme'


# Syntax highlighting (Hugo's built-in Chroma)
[markup]
  [markup.highlight]
    noClasses = true
    codeFences = true


[params]
  mainSections = ["Posts"]   # used by some list/home templates if referenced


[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3


[taxonomies]
tag = ""
category = ""
